import {
  DashboardStats,
  Resident,
  Alert,
  ActivityData,
  HealthMetric,
  MonitoringFeed,
  AlertRiskLevel,
  AlertSeverity,
  AlertStatus,
  AlertType,
} from '@/types'

export const mockStats: DashboardStats = {
  totalResidents: 24,
  activeAlerts: 7,
  camerasOnline: 12,
  avgResponseTime: 2.5,
  healthScore: 94,
  trends: [
    { label: 'Tổng cư dân', value: 24, change: 8.2 },
    { label: 'Cảnh báo hôm nay', value: 12, change: -15.3 },
    { label: 'Thời gian phản hồi TB', value: 2.5, change: -22.1 },
    { label: 'Điểm sức khỏe', value: 94, change: 3.4 },
  ],
}

export const mockResidents: Resident[] = [
  {
    id: '1',
    name: 'Nguyễn Thị Lan',
    age: 78,
    room: '201',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
    status: 'attention',
    lastActivity: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    healthMetrics: { heartRate: 88, bloodPressure: '130/85', activity: 65, sleep: 72 },
  },
  {
    id: '2',
    name: 'Trần Văn Minh',
    age: 82,
    room: '105',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    status: 'stable',
    lastActivity: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    healthMetrics: { heartRate: 72, bloodPressure: '120/80', activity: 80, sleep: 85 },
  },
  {
    id: '3',
    name: 'Phạm Thị Hương',
    age: 75,
    room: '302',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    status: 'critical',
    lastActivity: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    healthMetrics: { heartRate: 105, bloodPressure: '160/95', activity: 45, sleep: 58 },
  },
  {
    id: '4',
    name: 'Lê Văn Tuấn',
    age: 80,
    room: '108',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    status: 'stable',
    lastActivity: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    healthMetrics: { heartRate: 75, bloodPressure: '125/82', activity: 70, sleep: 78 },
  },
  {
    id: '5',
    name: 'Hoàng Thị Mai',
    age: 76,
    room: '205',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    status: 'stable',
    lastActivity: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    healthMetrics: { heartRate: 70, bloodPressure: '118/78', activity: 85, sleep: 90 },
  },
  {
    id: '6',
    name: 'Đặng Văn Hùng',
    age: 84,
    room: '310',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    status: 'attention',
    lastActivity: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    healthMetrics: { heartRate: 92, bloodPressure: '140/88', activity: 55, sleep: 65 },
  },
]

export interface FamilyRef {
  id: string
  name: string
  contact: string
  relationship: string
}

export interface DeviceRef {
  id: string
  name: string
  type: string
  location: string
  elderId?: string
}

export const mockFamilies: FamilyRef[] = [
  { id: 'F-001', name: 'Gia đình ông Hùng', contact: '0901 234 567', relationship: 'Con trai' },
  { id: 'F-002', name: 'Gia đình bà Lan', contact: '0912 345 678', relationship: 'Con gái' },
  { id: 'F-003', name: 'Gia đình bà Hương', contact: '0938 111 222', relationship: 'Con trai' },
  { id: 'F-004', name: 'Gia đình ông Tuấn', contact: '0977 888 555', relationship: 'Cháu' },
  { id: 'F-005', name: 'Gia đình bà Mai', contact: '0966 222 333', relationship: 'Con gái' },
  { id: 'F-006', name: 'Gia đình ông Minh', contact: '0944 555 666', relationship: 'Con trai' },
]

export const mockDevices: DeviceRef[] = [
  { id: 'CAM-001', name: 'Camera Phòng 201', type: 'Camera AI', location: 'Phòng 201', elderId: '1' },
  { id: 'CAM-002', name: 'Camera Phòng 105', type: 'Camera AI', location: 'Phòng 105', elderId: '2' },
  { id: 'CAM-003', name: 'Camera Phòng 302', type: 'Camera AI', location: 'Phòng 302', elderId: '3' },
  { id: 'CAM-004', name: 'Camera Phòng 108', type: 'Camera AI', location: 'Phòng 108', elderId: '4' },
  { id: 'CAM-005', name: 'Camera Hành lang T2', type: 'Camera AI', location: 'Hành lang tầng 2' },
  { id: 'CAM-006', name: 'Camera Phòng 310', type: 'Camera AI', location: 'Phòng 310', elderId: '6' },
  { id: 'SOS-001', name: 'Nút SOS cầm tay', type: 'SOS Button', location: 'Đeo tay', elderId: '6' },
  { id: 'WRIST-002', name: 'Vòng tay sức khỏe', type: 'Wearable', location: 'Đeo tay', elderId: '3' },
  { id: 'BED-002', name: 'Cảm biến giường', type: 'Bed Sensor', location: 'Phòng 105', elderId: '2' },
  { id: 'AI-ENGINE', name: 'AI Engine', type: 'System', location: 'Cloud' },
]

const alertTypeMeta: Record<AlertType, { risk: AlertRiskLevel; severity: AlertSeverity; title: string }> = {
  fall: { risk: 'HIGH', severity: 'critical', title: 'Phát hiện té ngã' },
  sos: { risk: 'HIGH', severity: 'critical', title: 'Tín hiệu SOS khẩn cấp' },
  medical: { risk: 'HIGH', severity: 'critical', title: 'Cảnh báo y tế khẩn cấp' },
  abnormal: { risk: 'MEDIUM', severity: 'warning', title: 'Hoạt động bất thường' },
  wander: { risk: 'MEDIUM', severity: 'warning', title: 'Đi lang thang bất thường' },
  vital: { risk: 'MEDIUM', severity: 'warning', title: 'Dấu hiệu sinh tồn bất thường' },
  medication: { risk: 'LOW', severity: 'info', title: 'Nhắc nhở uống thuốc' },
  system: { risk: 'LOW', severity: 'info', title: 'Sự cố hệ thống' },
}

const minutesAgo = (m: number) => new Date(Date.now() - 1000 * 60 * m).toISOString()
const hoursAgo = (h: number) => new Date(Date.now() - 1000 * 60 * 60 * h).toISOString()
const daysAgo = (d: number) => new Date(Date.now() - 1000 * 60 * 60 * 24 * d).toISOString()

const baseAlerts: Array<Omit<Alert, 'riskLevel' | 'severity' | 'status' | 'title'>> = [
  {
    id: 'AL-2401',
    type: 'fall',
    message: 'Phát hiện té ngã trong phòng ngủ - AI confidence 96%',
    description:
      'Hệ thống Camera AI ghi nhận chuyển động bất thường và tư thế nằm bất thường trong phòng 201 lúc 14:32. Người thân đã được thông báo tự động và đội ngũ y tế đang trên đường tới.',
    elderId: '1',
    elderName: 'Nguyễn Thị Lan',
    elderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop',
    elderAge: 78,
    elderRoom: '201',
    familyId: 'F-002',
    familyName: 'Gia đình bà Lan',
    familyContact: '0912 345 678',
    deviceId: 'CAM-001',
    deviceName: 'Camera Phòng 201',
    deviceType: 'Camera AI',
    deviceLocation: 'Phòng 201',
    confidence: 96,
    createdAt: minutesAgo(3),
    acknowledgedAt: minutesAgo(1),
    acknowledgedBy: 'Điều dưỡng Hoa',
    actions: [
      { id: 'a1', label: 'Thông báo gia đình', timestamp: minutesAgo(2), actor: 'Hệ thống' },
      { id: 'a2', label: 'Xác nhận tiếp nhận', timestamp: minutesAgo(1), actor: 'Điều dưỡng Hoa' },
    ],
  },
  {
    id: 'AL-2402',
    type: 'vital',
    message: 'Nhịp tim 105 bpm vượt ngưỡng an toàn (>100)',
    description:
      'Cảm biến đeo tay ghi nhận nhịp tim trung bình 105 bpm trong 10 phút liên tục. Có thể do vận động gắng sức hoặc bất ổn tim mạch.',
    elderId: '3',
    elderName: 'Phạm Thị Hương',
    elderAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop',
    elderAge: 75,
    elderRoom: '302',
    familyId: 'F-003',
    familyName: 'Gia đình bà Hương',
    familyContact: '0938 111 222',
    deviceId: 'WRIST-002',
    deviceName: 'Vòng tay sức khỏe',
    deviceType: 'Wearable',
    deviceLocation: 'Đeo tay',
    confidence: 92,
    createdAt: minutesAgo(12),
  },
  {
    id: 'AL-2403',
    type: 'sos',
    message: 'Người cao tuổi nhấn nút SOS khẩn cấp',
    description: 'Nút SOS cầm tay được kích hoạt. Vị trí: phòng 310. Đã kết nối với nhân viên trực.',
    elderId: '6',
    elderName: 'Đặng Văn Hùng',
    elderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop',
    elderAge: 84,
    elderRoom: '310',
    familyId: 'F-001',
    familyName: 'Gia đình ông Hùng',
    familyContact: '0901 234 567',
    deviceId: 'SOS-001',
    deviceName: 'Nút SOS cầm tay',
    deviceType: 'SOS Button',
    deviceLocation: 'Đeo tay',
    confidence: 100,
    createdAt: minutesAgo(25),
    acknowledgedAt: minutesAgo(23),
    acknowledgedBy: 'Bác sĩ Nam',
    resolvedAt: minutesAgo(8),
    resolvedBy: 'Bác sĩ Nam',
    actions: [
      { id: 'a1', label: 'Xác nhận SOS', timestamp: minutesAgo(23), actor: 'Bác sĩ Nam' },
      { id: 'a2', label: 'Tới phòng xử lý', timestamp: minutesAgo(18), actor: 'Bác sĩ Nam' },
      { id: 'a3', label: 'Đóng cảnh báo', timestamp: minutesAgo(8), actor: 'Bác sĩ Nam' },
    ],
  },
  {
    id: 'AL-2404',
    type: 'medication',
    message: 'Đã tới giờ uống thuốc huyết áp buổi chiều',
    description: 'Lịch uống thuốc: 14:00 mỗi ngày. Vòng tay sức khỏe xác nhận cư dân vẫn ổn định.',
    elderId: '2',
    elderName: 'Trần Văn Minh',
    elderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop',
    elderAge: 82,
    elderRoom: '105',
    familyId: 'F-006',
    familyName: 'Gia đình ông Minh',
    familyContact: '0944 555 666',
    deviceId: 'WRIST-002',
    deviceName: 'Vòng tay sức khỏe',
    deviceType: 'Wearable',
    deviceLocation: 'Đeo tay',
    confidence: 100,
    createdAt: minutesAgo(35),
  },
  {
    id: 'AL-2405',
    type: 'system',
    message: 'Camera CAM-006 mất kết nối với AI Engine',
    description: 'Camera AI tại phòng 310 không phản hồi tín hiệu trong 30 phút. Có thể do mất mạng.',
    elderId: '6',
    elderName: 'Đặng Văn Hùng',
    elderAge: 84,
    elderRoom: '310',
    familyId: 'F-001',
    familyName: 'Gia đình ông Hùng',
    familyContact: '0901 234 567',
    deviceId: 'CAM-006',
    deviceName: 'Camera Phòng 310',
    deviceType: 'Camera AI',
    deviceLocation: 'Phòng 310',
    createdAt: hoursAgo(1),
    acknowledgedAt: minutesAgo(50),
    acknowledgedBy: 'Kỹ thuật viên Tuấn',
    resolvedAt: minutesAgo(10),
    resolvedBy: 'Kỹ thuật viên Tuấn',
    actions: [
      { id: 'a1', label: 'Khởi động lại camera', timestamp: minutesAgo(20), actor: 'Kỹ thuật viên Tuấn' },
    ],
  },
  {
    id: 'AL-2406',
    type: 'abnormal',
    message: 'Không phát hiện chuyển động trong 4 giờ liên tục',
    description: 'Cảm biến giường và camera cho thấy cư dân không rời giường. Cần kiểm tra tình trạng sức khỏe.',
    elderId: '4',
    elderName: 'Lê Văn Tuấn',
    elderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop',
    elderAge: 80,
    elderRoom: '108',
    familyId: 'F-004',
    familyName: 'Gia đình ông Tuấn',
    familyContact: '0977 888 555',
    deviceId: 'BED-002',
    deviceName: 'Cảm biến giường',
    deviceType: 'Bed Sensor',
    deviceLocation: 'Phòng 108',
    confidence: 78,
    createdAt: hoursAgo(2),
    acknowledgedAt: hoursAgo(1),
    acknowledgedBy: 'Điều dưỡng Hoa',
    resolvedAt: minutesAgo(40),
    resolvedBy: 'Điều dưỡng Hoa',
    actions: [
      { id: 'a1', label: 'Gọi kiểm tra', timestamp: hoursAgo(1), actor: 'Điều dưỡng Hoa' },
    ],
  },
  {
    id: 'AL-2407',
    type: 'wander',
    message: 'Ra khỏi phòng lúc 2 giờ sáng - có dấu hiệu mất phương hướng',
    description: 'Camera hành lang phát hiện cư dân rời phòng vào khung giờ bất thường, đi vòng quanh không rõ mục đích.',
    elderId: '5',
    elderName: 'Hoàng Thị Mai',
    elderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop',
    elderAge: 76,
    elderRoom: '205',
    familyId: 'F-005',
    familyName: 'Gia đình bà Mai',
    familyContact: '0966 222 333',
    deviceId: 'CAM-005',
    deviceName: 'Camera Hành lang T2',
    deviceType: 'Camera AI',
    deviceLocation: 'Hành lang tầng 2',
    confidence: 88,
    createdAt: hoursAgo(5),
    acknowledgedAt: hoursAgo(4),
    acknowledgedBy: 'Bác sĩ Nam',
    resolvedAt: hoursAgo(3),
    resolvedBy: 'Bác sĩ Nam',
    actions: [
      { id: 'a1', label: 'Hỗ trợ về phòng', timestamp: hoursAgo(4), actor: 'Bác sĩ Nam' },
    ],
  },
  {
    id: 'AL-2408',
    type: 'medical',
    message: 'Huyết áp tăng cao đột ngột - 160/95 mmHg',
    description: 'Thiết bị đo huyết áp ghi nhận chỉ số vượt ngưỡng an toàn trên 3 lần đo liên tiếp.',
    elderId: '3',
    elderName: 'Phạm Thị Hương',
    elderAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop',
    elderAge: 75,
    elderRoom: '302',
    familyId: 'F-003',
    familyName: 'Gia đình bà Hương',
    familyContact: '0938 111 222',
    deviceId: 'WRIST-002',
    deviceName: 'Vòng tay sức khỏe',
    deviceType: 'Wearable',
    deviceLocation: 'Đeo tay',
    confidence: 95,
    createdAt: hoursAgo(7),
    acknowledgedAt: hoursAgo(6),
    acknowledgedBy: 'Bác sĩ Nam',
    resolvedAt: hoursAgo(4),
    resolvedBy: 'Bác sĩ Nam',
  },
  {
    id: 'AL-2409',
    type: 'system',
    message: 'AI Engine khởi động lại - downtime 2 phút',
    description: 'Hệ thống AI Engine tự khởi động lại để cập nhật model mới.',
    elderId: '',
    elderName: 'Toàn hệ thống',
    familyId: 'F-001',
    familyName: '—',
    deviceId: 'AI-ENGINE',
    deviceName: 'AI Engine',
    deviceType: 'System',
    deviceLocation: 'Cloud',
    createdAt: hoursAgo(10),
    acknowledgedAt: hoursAgo(10),
    acknowledgedBy: 'Hệ thống',
    resolvedAt: hoursAgo(10),
    resolvedBy: 'Hệ thống',
  },
  {
    id: 'AL-2410',
    type: 'medication',
    message: 'Đã tới giờ uống thuốc tiểu đường',
    description: 'Lịch uống thuốc: 19:00 hằng ngày.',
    elderId: '5',
    elderName: 'Hoàng Thị Mai',
    elderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop',
    elderAge: 76,
    elderRoom: '205',
    familyId: 'F-005',
    familyName: 'Gia đình bà Mai',
    familyContact: '0966 222 333',
    deviceId: 'WRIST-002',
    deviceName: 'Vòng tay sức khỏe',
    deviceType: 'Wearable',
    deviceLocation: 'Đeo tay',
    confidence: 100,
    createdAt: hoursAgo(12),
    acknowledgedAt: hoursAgo(11),
    acknowledgedBy: 'Điều dưỡng Hoa',
    resolvedAt: hoursAgo(10),
    resolvedBy: 'Điều dưỡng Hoa',
  },
  {
    id: 'AL-2411',
    type: 'abnormal',
    message: 'Rời khỏi giường > 5 lần trong đêm',
    description: 'Cảm biến giường ghi nhận cư dân rời giường nhiều lần, có thể do mất ngủ.',
    elderId: '4',
    elderName: 'Lê Văn Tuấn',
    elderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop',
    elderAge: 80,
    elderRoom: '108',
    familyId: 'F-004',
    familyName: 'Gia đình ông Tuấn',
    familyContact: '0977 888 555',
    deviceId: 'BED-002',
    deviceName: 'Cảm biến giường',
    deviceType: 'Bed Sensor',
    deviceLocation: 'Phòng 108',
    confidence: 81,
    createdAt: hoursAgo(18),
    acknowledgedAt: hoursAgo(17),
    acknowledgedBy: 'Bác sĩ Nam',
    resolvedAt: hoursAgo(15),
    resolvedBy: 'Bác sĩ Nam',
  },
  {
    id: 'AL-2412',
    type: 'fall',
    message: 'Té ngã nhẹ trong nhà tắm - không có chấn thương',
    description: 'AI phát hiện té ngã nhẹ trong nhà tắm. Cư dân tự đứng dậy được.',
    elderId: '2',
    elderName: 'Trần Văn Minh',
    elderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop',
    elderAge: 82,
    elderRoom: '105',
    familyId: 'F-006',
    familyName: 'Gia đình ông Minh',
    familyContact: '0944 555 666',
    deviceId: 'CAM-002',
    deviceName: 'Camera Phòng 105',
    deviceType: 'Camera AI',
    deviceLocation: 'Phòng 105',
    confidence: 73,
    createdAt: daysAgo(1),
    acknowledgedAt: daysAgo(1),
    acknowledgedBy: 'Điều dưỡng Hoa',
    resolvedAt: daysAgo(1),
    resolvedBy: 'Điều dưỡng Hoa',
  },
  {
    id: 'AL-2413',
    type: 'vital',
    message: 'SpO2 giảm xuống 91% trong 5 phút',
    description: 'Nồng độ oxy trong máu giảm nhẹ dưới ngưỡng an toàn.',
    elderId: '3',
    elderName: 'Phạm Thị Hương',
    elderAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop',
    elderAge: 75,
    elderRoom: '302',
    familyId: 'F-003',
    familyName: 'Gia đình bà Hương',
    familyContact: '0938 111 222',
    deviceId: 'WRIST-002',
    deviceName: 'Vòng tay sức khỏe',
    deviceType: 'Wearable',
    deviceLocation: 'Đeo tay',
    confidence: 89,
    createdAt: daysAgo(1),
    acknowledgedAt: daysAgo(1),
    acknowledgedBy: 'Bác sĩ Nam',
    resolvedAt: daysAgo(1),
    resolvedBy: 'Bác sĩ Nam',
  },
  {
    id: 'AL-2414',
    type: 'medication',
    message: 'Bỏ lỡ uống thuốc sáng nay',
    description: 'Cảm biến không ghi nhận việc uống thuốc theo lịch 08:00.',
    elderId: '5',
    elderName: 'Hoàng Thị Mai',
    elderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop',
    elderAge: 76,
    elderRoom: '205',
    familyId: 'F-005',
    familyName: 'Gia đình bà Mai',
    familyContact: '0966 222 333',
    deviceId: 'WRIST-002',
    deviceName: 'Vòng tay sức khỏe',
    deviceType: 'Wearable',
    deviceLocation: 'Đeo tay',
    confidence: 100,
    createdAt: daysAgo(1),
    acknowledgedAt: daysAgo(1),
    acknowledgedBy: 'Điều dưỡng Hoa',
    resolvedAt: daysAgo(1),
    resolvedBy: 'Điều dưỡng Hoa',
  },
  {
    id: 'AL-2415',
    type: 'medical',
    message: 'Đường huyết tăng cao 220 mg/dL sau bữa trưa',
    description: 'Chỉ số đường huyết vượt ngưỡng an toàn sau bữa ăn.',
    elderId: '6',
    elderName: 'Đặng Văn Hùng',
    elderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop',
    elderAge: 84,
    elderRoom: '310',
    familyId: 'F-001',
    familyName: 'Gia đình ông Hùng',
    familyContact: '0901 234 567',
    deviceId: 'WRIST-002',
    deviceName: 'Vòng tay sức khỏe',
    deviceType: 'Wearable',
    deviceLocation: 'Đeo tay',
    confidence: 91,
    createdAt: daysAgo(2),
    acknowledgedAt: daysAgo(2),
    acknowledgedBy: 'Bác sĩ Nam',
    resolvedAt: daysAgo(2),
    resolvedBy: 'Bác sĩ Nam',
  },
  {
    id: 'AL-2416',
    type: 'wander',
    message: 'Đi vào khu vực cấm - cửa thoát hiểm',
    description: 'Cư dân đi tới khu vực cửa thoát hiểm tầng 3 lúc 23h.',
    elderId: '1',
    elderName: 'Nguyễn Thị Lan',
    elderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop',
    elderAge: 78,
    elderRoom: '201',
    familyId: 'F-002',
    familyName: 'Gia đình bà Lan',
    familyContact: '0912 345 678',
    deviceId: 'CAM-005',
    deviceName: 'Camera Hành lang T2',
    deviceType: 'Camera AI',
    deviceLocation: 'Hành lang tầng 2',
    confidence: 85,
    createdAt: daysAgo(2),
    acknowledgedAt: daysAgo(2),
    acknowledgedBy: 'Bảo vệ Lâm',
    resolvedAt: daysAgo(2),
    resolvedBy: 'Bảo vệ Lâm',
  },
  {
    id: 'AL-2417',
    type: 'fall',
    message: 'Nghi ngờ té ngã - chưa xác nhận',
    description: 'AI confidence thấp 62%, cần nhân viên kiểm tra lại.',
    elderId: '4',
    elderName: 'Lê Văn Tuấn',
    elderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop',
    elderAge: 80,
    elderRoom: '108',
    familyId: 'F-004',
    familyName: 'Gia đình ông Tuấn',
    familyContact: '0977 888 555',
    deviceId: 'CAM-004',
    deviceName: 'Camera Phòng 108',
    deviceType: 'Camera AI',
    deviceLocation: 'Phòng 108',
    confidence: 62,
    createdAt: daysAgo(3),
    acknowledgedAt: daysAgo(3),
    acknowledgedBy: 'Điều dưỡng Hoa',
    resolvedAt: daysAgo(3),
    resolvedBy: 'Điều dưỡng Hoa',
  },
  {
    id: 'AL-2418',
    type: 'system',
    message: 'Cập nhật firmware cho camera CAM-002',
    description: 'Bảo trì định kỳ, hoàn tất sau 8 phút.',
    elderId: '2',
    elderName: 'Trần Văn Minh',
    elderAge: 82,
    elderRoom: '105',
    familyId: 'F-006',
    familyName: 'Gia đình ông Minh',
    familyContact: '0944 555 666',
    deviceId: 'CAM-002',
    deviceName: 'Camera Phòng 105',
    deviceType: 'Camera AI',
    deviceLocation: 'Phòng 105',
    createdAt: daysAgo(3),
    acknowledgedAt: daysAgo(3),
    acknowledgedBy: 'Kỹ thuật viên Tuấn',
    resolvedAt: daysAgo(3),
    resolvedBy: 'Kỹ thuật viên Tuấn',
  },
]

function inferStatus(a: { acknowledgedAt?: string; resolvedAt?: string }, explicit?: AlertStatus): AlertStatus {
  if (explicit) return explicit
  if (a.resolvedAt) return 'resolved'
  if (a.acknowledgedAt) return 'in_progress'
  return 'new'
}

export const mockAlerts: Alert[] = baseAlerts.map((a) => {
  const meta = alertTypeMeta[a.type]
  return {
    ...a,
    title: meta.title,
    riskLevel: meta.risk,
    severity: meta.severity,
    status: inferStatus(a, (a as { status?: AlertStatus }).status),
  }
})

export const mockActivityData: ActivityData[] = Array.from({ length: 24 }, (_, i) => ({
  time: `${String(i).padStart(2, '0')}:00`,
  residents: Math.floor(Math.random() * 10) + 5,
  alerts: Math.floor(Math.random() * 5),
}))

export const mockHealthMetrics: HealthMetric[] = Array.from({ length: 7 }, (_, i) => ({
  time: `Ngày ${i + 1}`,
  heartRate: Math.floor(Math.random() * 20) + 65,
  activity: Math.floor(Math.random() * 30) + 50,
  sleep: Math.floor(Math.random() * 25) + 65,
}))

export const mockMonitoringFeed: MonitoringFeed[] = [
  {
    id: '1',
    cameraId: 'CAM-001',
    cameraName: 'Phòng 201',
    status: 'online',
    lastFrame: new Date().toISOString(),
    currentActivity: 'Đang ngồi nghỉ',
    alerts: 1,
  },
  {
    id: '2',
    cameraId: 'CAM-002',
    cameraName: 'Phòng 105',
    status: 'online',
    lastFrame: new Date().toISOString(),
    currentActivity: 'Đang ngủ',
    alerts: 0,
  },
  {
    id: '3',
    cameraId: 'CAM-003',
    cameraName: 'Phòng 302',
    status: 'online',
    lastFrame: new Date().toISOString(),
    currentActivity: 'Đang đi lại',
    alerts: 2,
  },
  {
    id: '4',
    cameraId: 'CAM-004',
    cameraName: 'Phòng 108',
    status: 'recording',
    lastFrame: new Date().toISOString(),
    currentActivity: 'Đang xem TV',
    alerts: 0,
  },
  {
    id: '5',
    cameraId: 'CAM-005',
    cameraName: 'Hành lang T2',
    status: 'online',
    lastFrame: new Date().toISOString(),
    currentActivity: 'Không có hoạt động',
    alerts: 0,
  },
  {
    id: '6',
    cameraId: 'CAM-006',
    cameraName: 'Phòng 310',
    status: 'offline',
    lastFrame: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    currentActivity: 'Offline',
    alerts: 1,
  },
]
